comment:
  layout: "header, diff, changes, tree"
  behavior: default

ignore:
  - "PackageInfo.g"
  - "init.g"
  - "read.g"
  - "tst/*"     # ignore test harness code
  - "tst/**/*"  # ignore test harness code
