name: Repsn
version: 3.0.2dev
date: 2011-08-25
description: |
    Constructing representations of finite groups

authors:
    - name: Vahid Dabbaghian
      url: http://www.sfu.ca/~vdabbagh

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">= 4.8"

www: https://gap-packages.github.io/repsn/
readme: README.md
packageinfo: https://gap-packages.github.io/repsn/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/repsn/releases/download/v3.0.2dev/repsn-3.0.2dev.tar.gz

abstract: |
    The package provides <span class="pkgname">GAP</span> functions for computing characteristic zero matrix representations of finite groups.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    group representations, matrix representations, Dixon's method.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>DT11</span>]   <b class='BibAuthor'>Dabbaghian, V. and GAP Team, T.</b>,
     <i class='BibTitle'>Repsn, Constructing representations of finite groups,
             Version 3.0.2dev</i>
     (<span class='BibYear'>2011</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/repsn/">https://gap-packages.github.io/repsn/</a></span>.
    </p>
    

bibtex: |
    @misc{ Repsn3.0.2dev,
      author =           {Dabbaghian, V. and GAP Team, T.},
      title =            {{Repsn}, Constructing representations of finite groups, {V}ersion 3.0.2dev},
      month =            {Aug},
      year =             {2011},
      note =             {Refereed GAP package},
      howpublished =     {\href                                              {https://gap-packages.github.io/repsn/}
                          {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{repsn/}}},
      keywords =         {group representations; matrix representations; Dixon's method},
      printedkey =       {DT11}
    }

